### ISSUE TITLE
verbose mode

### ISSUE THREAD

**Issue by SamVerschueren** [vadimdemedes/trevor#12]
I think it would be nice if we had a verbose mode that logs all the output per container.

``` sh
trevor --verbose
```

**Comment by vdemedes** [comment]
Good one!

**Comment by gabrielcsapo** [comment]
would this also help with #42 ? Verbose would output logs and show any build information?

**Comment by vadimdemedes** [comment]
I changed my mind on this one, because I don't think there's any real benefit to showing all output from the container (except on error). Since Trevor can run multiple builds concurrently, I don't see how we can cleanly display the output from multiple containers.
