### ISSUE TITLE
Linking containers

### ISSUE THREAD

**Issue by SamVerschueren** [vadimdemedes/trevor#2]
First of all, awesome project!

I was thinking, wouldn't it be nice if we could link containers? In travis it is for instance possible to get access to a mongodb database to test queries and such.

``` yml
language: node_js
services:
  - mongodb
node_js:
  - 'stable'
```

If one would pass in this yaml file, it would link `mongodb` to the container that executes the test with the name `mongodb`.

``` sh
$ docker run --rm --link mongodb:mongodb my_container npm test
```

Where it is up to the user to make sure the `mongodb` container is running. Instead of connecting with an IP adres like this `mongodb://localhost:27017/exampleDb`, you would connect with the container like this `mongodb://mongodb:27017/exampleDb`.

If you like the idea, would be happy to do a PR.

**Comment by SamVerschueren** [comment]
More information can be found in PR https://github.com/vdemedes/trevor/pull/3

**Comment by vadimdemedes** [comment]
Closing, I'll try to keep it simple for the nearest time.
