### ISSUE TITLE
Trevor expects a package.json

### ISSUE THREAD

**Issue by Haroenv** [vadimdemedes/trevor#36]
Travis works for other environments than node, should Trevor support this too?

```sh
$ trevor

  error package.json does not exist in the current directory
```

**Comment by SamVerschueren** [comment]
This would make it far too complex imo.

**Comment by Haroenv** [comment]
Makes perfect sense, there's a reason *real* travis ci is way bigger than this.

**Comment by vadimdemedes** [comment]
Agree with @SamVerschueren, we'd like to keep Trevor simple and great at solving a specific problem.
