### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by vkbansal** [vadimdemedes/trevor#38]
I'm unable to install trevor.

OS: MacOS Sierra 10.12.3
node: v7.5.0
npm: v4.1.2
Docker: 1.13.1 (15353)
command: `npm install -g trevor`

```
14417 error Darwin 16.4.0
14418 error argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "install" "-g" "trevor"
14419 error node v7.5.0
14420 error npm  v4.1.2
14421 error path /usr/local/lib/node_modules/trevor/cli.js
14422 error code ENOENT
14423 error errno -2
14424 error syscall chmod
14425 error enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/trevor/cli.js'
14426 error enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/trevor/cli.js'
14426 error enoent This is most likely not a problem with npm itself
14426 error enoent and is related to npm not being able to find a file.
14427 verbose exit [ -2, true ]
```

Entire log file can be [found here](https://gist.github.com/vkbansal/550e30e1b4b50225fe699d3cf91bda76)

**Comment by SamVerschueren** [comment]
Have you installed node as sudo?

**Comment by vkbansal** [comment]
Nope.

I installed node using brew.

I also tried `sudo npm install -g trevor`. Got same error.

**Comment by jwilsson** [comment]
I'm getting the same error.

I think it's due to `cli.js` missing from the `files` array in `package.json`.

**Comment by vadimdemedes** [comment]
Such an annoying mistake... Pushed up a patch (`2.0.1`), should be working now. Thanks for reporting @vkbansal and @jwilsson!

**Comment by vadimdemedes** [comment]
These kind of mistakes when doing releases are so annoying and easy to miss. This needs to be fixed once and for all. I think an eslint rule might work (added to todo).
