### ISSUE TITLE
Can't run trevor command

### ISSUE THREAD

**Issue by Exelord** [vadimdemedes/trevor#41]
Hi,
after installation I can not run the `trevor` command:
```
/Users/exelord/.nvm/versions/node/v4.5.0/lib/node_modules/trevor/cli.js:8
const {STATE_ERROR} = require('./lib/states');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

**Comment by SamVerschueren** [comment]
Apparently Trevor needs Node 6+. 

@vadimdemedes Is that on purpose? Maybe we should specify the engines property in package.json.

**Comment by vadimdemedes** [comment]
Yes, Trevor requires Node.js v6+ and it's on purpose. Since it's a CLI tool and it's not getting deployed inside any apps, I think it's better and easier for a user to upgrade to the latest LTS.

> Maybe we should specify the engines property in package.json.

Yes, definitely!

**Comment by vadimdemedes** [comment]
Closing in favor of https://github.com/vadimdemedes/trevor/issues/45.
