### ISSUE TITLE
Logs from the containers

### ISSUE THREAD

**Issue by markelog** [vadimdemedes/trevor#42]
Would it be possible for you to provide a way to get output from the containers? Since now I only see

>    ✖  4:  error
   ✖  5:  error
   ✖  6:  error
   ✖  7:  error

:)

**Comment by vadimdemedes** [comment]
Yes, definitely a must have!

**Comment by vadimdemedes** [comment]
Error output added in `2.1.0` release ;)

**Comment by vadimdemedes** [comment]
![screen shot 2017-02-18 at 8 14 00 pm](https://cloud.githubusercontent.com/assets/697676/23095695/cb571316-f616-11e6-8d9e-238c91023447.png)

**Comment by sanex3339** [comment]
Also it would be nice to output errors instanly as error occurs without waiting of all images to finish (or error)

**Comment by markelog** [comment]
Awesome, thanks a lot!
