### ISSUE TITLE
Trevor only runs nodejs

### ISSUE THREAD

**Issue by gabrielcsapo** [vadimdemedes/trevor#44]
Right now the [we are manually creating the docker file image](https://github.com/vadimdemedes/trevor/blob/master/lib/build.js), but travis has open sourced their build script to do this for us. https://github.com/travis-ci/travis-build

Another issue is that when we build this ourselves parsing the YML should be a 1:1 with how Travis does it. 

Do you think we should move to integrate (https://github.com/vadimdemedes/trevor/blob/master/lib/build.js) as the way to build docker files?

**Comment by vadimdemedes** [comment]
I think I'm going to leave Trevor Node.js-only for a while for the sake of simplicity and ease of maintenance, but if enough people request this feature, I'm happy to reconsider that decision. Thanks for the suggestion!
