### ISSUE TITLE
builds silently fail?

### ISSUE THREAD

**Issue by onel0p3z** [vadimdemedes/trevor#59]
Not sure if there's a way to check why builds fail. Currently, I have a project in which builds fail without providing an error message. How can I access logs or debug the build? Please advise. Thank you!

This is the output when i run trevor:
```
$ trevor

   ✖  4:  error
   ✖  6:  error
```

**Comment by vadimdemedes** [comment]
Looks like you're using an out-dated version, make sure to update and let me know if it solved the issue? If not, we'll see what's the root of this.

**Comment by onel0p3z** [comment]
oh my ... I definitely was running an older version. 
```
$ npm ls -g | grep trevor
├─┬ trevor@2.0.1 
```
Just updated to `2.3.0` and problems are gone. **Thank you!**

**Comment by vadimdemedes** [comment]
No probs, glad Trevor is helping you ;)
