### ISSUE TITLE
✖ package.json doesn't exist and other install issues

### ISSUE THREAD

**Issue by coder0xff** [vadimdemedes/trevor#66]
I used:

    sudo npm install --global trevor

To install. Upon running, I was told that `node` did not exist. On Ubuntu 16.04.3 LTS I ran:

    sudo apt install node

and on Debian Jesse 8.1:

    curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

On Ubuntu this gave /usr/bin/nodejs but not /usr/bin/node as required.  For Ubuntu I created a symlink. However, now when I run Trevor on Debian I get:

     ✖ package.json doesn't exist

And on Ubuntu I get:

```
/usr/local/lib/node_modules/trevor/cli.js:8
const {STATE_ERROR} = require('./lib/states');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Which I have no idea how to fix either. More complete information on the prerequisies, installation, invocation, and troubleshooting would be very helpful.

**Comment by Sbitneva** [comment]
Same problem. I've tried to create package.json with
```bash
npm init -y
```
inside my `.travis.yml`'s path and restart trevor, as a result `✖ package.json doesn't exist` error disappeared. However, I didn't notice that travor for node.js only and now I got `✖ Language java isn't supported` :disappointed:. Anyway, maybe it will be helpful.

**Comment by vadimdemedes** [comment]
Not sure I understand, how is this related to Trevor?

**Comment by coder0xff** [comment]
I've decided to use Jenkins instead. Feel free to close this issue if it suits you.

**Comment by shreyasminocha** [comment]
@vadimdemedes Does Trevor support only node.js? I'm getting a `✖ package.json` error as well.

**Comment by vadimdemedes** [comment]
It supports only Node.js at this moment and will probably stay this way, unless there's a simple and elegant way to make it universal.
