### ISSUE TITLE
Fails on Node version 10 or "stable".

### ISSUE THREAD

**Issue by jbenner-radham** [vadimdemedes/trevor#67]
Currently I'm getting the following error when I have either `10` or `stable` set as values in my `.travis.yml` file:

```sh
➜  node-readme-md-cli git:(master) ✗ npx trevor       
(node:41439) ExperimentalWarning: The fs.promises API is experimental

 ◌ 7:  downloading base image
 ◌ 8:  downloading base image
 ◌ 9:  downloading base image
 ✖ 10: error
Error: ENOENT: no such file or directory, unlink '/Users/jbenner/Documents/github/jbenner-radham/node-readme-md-cli/.10.dockerfile'
```

After some quick research it appears the issue is that Trevor pulls the Docker image via `node:${context.version}-onbuild` but "onbuild" images were deprecated as per this [issue](https://github.com/docker-library/official-images/issues/2076) and it appears that starting with the `node:10` Docker image they have begun omitting the "onbuild" image as seen by it's absence [here](https://github.com/nodejs/docker-node/tree/master/10).

If it's OK I'd like to submit a pull request to resolve the issue since Trevor is such an awesome piece of software I'd love to help contribute back to it.

**Comment by vadimdemedes** [comment]
Absolutely, feel free to fix this, I'd appreciate it! ❤️

**Comment by jbenner-radham** [comment]
Awesome, thank you! Just one quick question, for all the Node versions prior to 10 should I still have it pull the `node:${context.version}-onbuild` images or would you prefer to just keep it uniform and just pull the `node:${context.version}` images for every Node version now?

**Comment by jbenner-radham** [comment]
Cool, thank you!

I just submitted a pull request. It's no longer using any `onbuild` images whatsoever but I did implement the relevant `Dockerfile` commands from [`node:9-onbuild`](https://github.com/nodejs/docker-node/blob/9023f588717d236a92d91a8483ff0582484c22d1/9/onbuild/Dockerfile) to stay as consistent as possible to the prior implementation.

If there's anything you'd like me to change or refactor please just let me know and I'd be happy to do so.

Thanks!
